### ISSUE TITLE
Generate API access token

### ISSUE THREAD

**Issue by hurtleturtle** [generatom/snake#3]
1. Create a stubhub developer account
2. Create an ordinary stubhub account
3. Generate an API access token by doing following the steps in https://developer.stubhub.com/getting-started
4. Verify that it works by searching https://api.stubhub.com/sellers/search/events/v3?q=london (don't forget to change your authorization header so that it reads something like the below)
`Authorization: Bearer <your access token from step 3>`

**Comment by hobzee** [comment]
Access granted
